import {
  aiAutomodBatchSize,
  aiAutomodCryptoScam,
  aiAutomodDoxxing,
  aiAutomodEnabled,
  aiAutomodHate,
  aiAutomodImpersonation,
  aiAutomodNsfw,
  aiAutomodRaid,
  aiAutomodScam,
  aiAutomodSelfharm,
  aiAutomodSentiment,
  aiAutomodSpamAd,
  aiAutomodToxicity,
  aiAutomodVisionEnabled,
  aiMonitoringNotice,
  automodEnabled,
  heatedSlowmodeSeconds,
  raidJoinThreshold,
  raidJoinWindowSec,
  raidNewAccountAlertEnabled,
  urlRiskEnabled,
} from '../config.ts'

export function formatModAutomodStatus(): string {
  const lines = [
    '**Rule AutoMod**',
    `• enabled: ${automodEnabled}`,
    `• URL heuristics: ${urlRiskEnabled}`,
    '',
    '**AI AutoMod**',
    `• enabled: ${aiAutomodEnabled}`,
    `• batch size: ${aiAutomodBatchSize}`,
    `• toxicity: ${aiAutomodToxicity} | hate: ${aiAutomodHate} | selfharm: ${aiAutomodSelfharm}`,
    `• scam: ${aiAutomodScam} | crypto_scam: ${aiAutomodCryptoScam} | spam_ad: ${aiAutomodSpamAd}`,
    `• nsfw: ${aiAutomodNsfw} | doxxing: ${aiAutomodDoxxing} | evasion: on`,
    `• impersonation: ${aiAutomodImpersonation} | sentiment/heated: ${aiAutomodSentiment}`,
    `• vision: ${aiAutomodVisionEnabled}`,
    `• heated slowmode: ${heatedSlowmodeSeconds}s (0=off)`,
    '',
    '**Raid**',
    `• join tracking: ${aiAutomodRaid} | threshold ${raidJoinThreshold} in ${raidJoinWindowSec}s`,
    `• new-account alerts: ${raidNewAccountAlertEnabled}`,
    '',
    '**User-facing notice**',
    aiMonitoringNotice,
  ]
  return lines.join('\n')
}
